name: Build bawa binary

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build bawa
        run: cargo install bawa --root ./output

      - name: Create Release and Upload Binary
        uses: softprops/action-gh-release@v2
        with:
          tag_name: bawa-v0.1.0
          name: bawa v0.1.0
          files: output/bin/bawa
